create table card
(
    balance integer not null,
    id      bigint generated by default as identity,
    user_id bigint,
    primary key (id),
    check (balance >= 0)
);

create table transaction
(
    transaction_value integer      not null,
    card_id           bigint,
    date_time         timestamp(6) not null,
    id                bigint generated by default as identity,
    type              varchar(10)  not null check (type in ('INCOME', 'OUTCOME', 'REFUND')),
    primary key (id)
);

create table users
(
    id        bigint generated by default as identity,
    user_name varchar(255) not null,
    primary key (id)
);

alter table if exists card
    add constraint card_users_fk
    foreign key (user_id)
    references users;

alter table if exists transaction
    add constraint transaction_card_fk
    foreign key (card_id)
    references card;