create table roles (
    id bigint generated by default as identity,
    role varchar(20) check (role in ('ROLE_USER','ROLE_ADMIN')),
    primary key (id)
);

create table user_roles (
    role_id bigint not null,
    user_id bigint not null,
    primary key (role_id, user_id)
);

alter table users add password varchar(255) not null default '$2a$12$IzP7n8.HaFL/yy7qyduUsODbMI7q.m1IvrWpsBrK./fjjBev2akPS';

alter table if exists user_roles
    add constraint user_roles_roles_fk
    foreign key (role_id)
    references roles;

alter table if exists user_roles
    add constraint user_roles_users_fk
    foreign key (user_id)
    references users;